"""
REST API Router for Industrial Multi-PLC Pipeline Simulator.
Exposes endpoints to monitor, start, stop, configure scenarios,
and inspect real-time industrial protocol frames.
"""

from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.services.plc_pipeline_simulator import plc_pipeline

router = APIRouter(prefix="/api/pipeline", tags=["PLC Pipeline Simulator"])


class StartPipelineRequest(BaseModel):
    interval_sec: Optional[float] = 2.0
    scenario: Optional[str] = "NORMAL"


class ScenarioRequest(BaseModel):
    scenario: str


class ConfigPipelineRequest(BaseModel):
    interval_sec: Optional[float] = 2.0
    scenario: Optional[str] = "NORMAL"


@router.get("/status")
def get_pipeline_status():
    """Returns the operational status, current scenario, and frame statistics of the PLC pipeline."""
    return {
        "success": True,
        "status": plc_pipeline.get_status()
    }


@router.post("/start")
def start_pipeline(req: Optional[StartPipelineRequest] = None):
    """Starts the real-time background PLC pipeline."""
    interval = req.interval_sec if req and req.interval_sec else 2.0
    scenario = req.scenario if req and req.scenario else "NORMAL"
    plc_pipeline.set_scenario(scenario)
    plc_pipeline.start(interval_sec=interval)
    return {
        "success": True,
        "message": f"PLC Data Pipeline đã khởi động thành công (Tần số: {interval}s, Kịch bản: {scenario})",
        "status": plc_pipeline.get_status()
    }


@router.post("/stop")
def stop_pipeline():
    """Stops the real-time PLC pipeline."""
    plc_pipeline.stop()
    return {
        "success": True,
        "message": "PLC Data Pipeline đã tạm dừng.",
        "status": plc_pipeline.get_status()
    }


@router.post("/scenario")
def set_pipeline_scenario(req: ScenarioRequest):
    """Switches the plant operational scenario (NORMAL, TAKT_CREEP, BOTTLENECK_SURGE, DEFECT_SPIKE)."""
    ok = plc_pipeline.set_scenario(req.scenario)
    if not ok:
        raise HTTPException(
            status_code=400,
            detail=f"Kịch bản '{req.scenario}' không hợp lệ! Chọn: NORMAL, TAKT_CREEP, BOTTLENECK_SURGE, DEFECT_SPIKE"
        )
    return {
        "success": True,
        "message": f"Đã chuyển kịch bản xưởng sang: {req.scenario.upper()}",
        "status": plc_pipeline.get_status()
    }


@router.post("/tick")
def trigger_manual_tick():
    """Triggers an instantaneous single pipeline tick across all 5 plant stations."""
    res = plc_pipeline.execute_tick()
    return {
        "success": True,
        "message": "Đã thực thi 1 chu kỳ quét đồng bộ qua 5 trạm PLC!",
        "result": res
    }


@router.get("/frames")
def get_recent_frames(limit: int = 15):
    """Returns recent industrial protocol frames generated by the pipeline (OPC-UA, Modbus-TCP, MQTT)."""
    frames = plc_pipeline.get_recent_frames(limit=limit)
    return {
        "success": True,
        "count": len(frames),
        "frames": frames
    }
